### PR TITLE
Add Signing to project.

### PR DESCRIPTION
**Pull request by mabreuortega**
Add Signing settings to project.
Fix build command for repository paths with spaces.

### CODE REVIEW

**Comment by ryanvgates** [comment]
@mabreuortega Can you create an issue in this repository for this pull request? And I'd like to publish two separate packages, one signed and one unsigned.

**Comment by mabreuortega** [comment]
#87

**Comment by ses4j** [comment]
@ryanvgates FWIW, I don't think there's any need/value in publishing an unsigned one.

**Comment by ryanvgates** [comment]
@ses4j I'm not sure I agree with you on that. I may be wrong, but I believe adding a reference to a signed assembly requires that the project be signed as well. I've worked on many projects that didn't require signing. I think most nuget packages that support it do publish both.

**Comment by ses4j** [comment]
@ryanvgates Not true - for example, this project references a bunch of `System.*` dlls, which are all signed by Microsoft.  Additionally, see, for instance: https://stackoverflow.com/a/8784917/237091

> In other words, ANY assembly can use a strongly signed assembly. But a strongly signed assembly can only use OTHER strongly signed assemblies.

**Comment by JonathanMagnan** [comment]
Hello,

This pull will be closed since this repo is no longer maintained.

We recommend you to move to [System.Linq.Dynamic.Core](https://github.com/zzzprojects/System.Linq.Dynamic.Core) instead. If the bug still exists in this repo, you can create an issue and link to this pull or create a new pull and we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Pull request closed without merging**
