### PR TITLE
#63 - Changed Dictionary<Signature,Type> to ConcurrentDictionary<Sign…

### PR DESCRIPTION
**Pull request by TWhidden**
Issue/Request #63 - Changed Dictionary<Signature,Type> to ConcurrentDictionary<Signature,Type> to fix error when key already exists.

### CODE REVIEW

**Comment by ryanvgates** [comment]
Can you add some unit tests to prove that the case has been resolved?

**Comment by mobilebilly** [comment]
The problem should have been fixed in https://github.com/kahanu/System.Linq.Dynamic/pull/48 with a ReaderWriterLock

**Comment by TWhidden** [comment]
Hi @ryanvgates , @mobilebilly  looks to have some test cases in that request.  The question is if the possible extra cycles of a non-atomic operation is acceptable using the ConcurrentDictionary<>, or if us using a Reader/Writer lock is OK.  I find it is cleaner using ConcurrenctDictionary though I can see the reason for using the other #48 usage.  Regardless of the route chose, it is important to get one of these options merged in, because without it, multi-threaded operations will cause a crash.

**Comment by JonathanMagnan** [comment]
Hello,

This pull will be closed since this repo is no longer maintained since 2016.

We recommend you to move to [System.Linq.Dynamic.Core](https://github.com/zzzprojects/System.Linq.Dynamic.Core) instead. If the bug still exists in this repo, you can create an issue and link to this pull or create a new pull and we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Pull request closed without merging**
