### PR TITLE
Updated System.Linq.Dynamic projects to multi target project including .net 4.0 & .net standard 2.0 + Use new csproj's nuget package & nuspec integration instead of separated nuget.exe & nuspec file

### PR DESCRIPTION
**Pull request by ysmoradi**
Note that the nuget package you create using this new project produces the same assembly for existing developers. It's based on .net 4.0 & has no new dependency.
But it also produces the .net standard 2.0 compatible binary using multi-targeting feature of cs projects.
Please accept this PR and release its nuget package, so we can use this in xamarin ios / android projects + uwp projects and web assembly projects too. Thanks in advance (:

### CODE REVIEW

**Comment by ysmoradi** [comment]
You can find new nuspec in cs proj of your project. Take a look at
https://github.com/kahanu/System.Linq.Dynamic/pull/85/files#diff-894845b9bdf82f065a7f2996bd0f36d1R17

**Comment by ysmoradi** [comment]
Either this project with my changes or your project have dependency on system.reflection.emit
I can't use any of these nuget packages on a multi-target android/ios project. On the same project, ef core which has dependency on sys.ref.emit is working properly :-S

**Comment by ryanvgates** [comment]
I apologize for the really long delay on this. I'll have to take a look, but I can't really make any commitments about releasing anything.

**Comment by JonathanMagnan** [comment]
Hello,

This pull will be closed since this repo is no longer maintained.

We recommend you to move to [System.Linq.Dynamic.Core](https://github.com/zzzprojects/System.Linq.Dynamic.Core) instead. If the bug still exists in this repo, you can create an issue and link to this pull or create a new pull and we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Pull request closed without merging**
